import Head from 'next/head'
import Footer from '../components/Footer'
import SliderAudio from '../components/SliderAudio'
import Title from '../components/Title'

export default function Home() {

  let user = {
    id: 1,
    nom: "pierru",
    prenom: "gaetan",
    email: "pierrugaetan0@gmail.com",
    isAdmin: true
  }


  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Title name={user.prenom} className />
        {
          user.isAdmin ? <> <p> tu as les super pouvoir</p>  </> : <p>tu es une merde</p>
        }

        <SliderAudio />
      </main>

      <Footer />
    </div>
  )
}
